### ISSUE TITLE
Using scoped package has broken npm installation for v0.10

### ISSUE THREAD

**Issue by shnist** [kevva/mount-point#2]
Hi,

I'm currently using node v0.10 and I receive the following error when attempting to install this package:

```
npm ERR! 404 404 Not Found: sindresorhus
npm ERR! 404
npm ERR! 404 'sindresorhus' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'mount-point'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Darwin 14.3.0
npm ERR! command "/Volumes/Data/Users/fabera/.nvm/v0.10.38/bin/node" "/Volumes/Data/Users/fabera/.nvm/v0.10.38/bin/npm" "install"
npm ERR! cwd /Volumes/Data/Users/fabera/Sites/tempus-nw-audiomator/nwapp
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! not ok code 0
```

I believe this is because scope packages are not supported in the version of npm that comes bundled with node v0.10.

Could you please at least update your readme to indicate that this breaking change has occurred for versions 1.2 and above.

Thanks

**Comment by shinnn** [comment]
Updating npm to the latest version fixes this problem. Just run:

```
npm i -g npm
```

**Comment by shinnn** [comment]
(Sorry, I unintentionally closed this issue.)

**Comment by kevva** [comment]
Upgrading npm **does** solve the issue (just tested). `1.4.28` is ancient.
