### ISSUE TITLE
Hangs on unopened-for-write fifo files

### ISSUE THREAD

**Issue by eush77** [kevva/mount-point#4]
Steps to reproduce:

```
$ mkfifo a.fifo
$ node -e 'require(".")("a.fifo").then(console.log)'
# (hangs)
```

The reason is that `df` gets stuck trying to `open(2)` a fifo and waiting for the other end:

```
$ strace df -kP a.fifo
# ...
# open("a.fifo", O_RDONLY|O_NOCTTY
# (hangs)
```

This behavior is well described in `fifo(7)`:

```
The FIFO must be opened  on  both
ends  (reading  and writing) before data can be passed.  Normally, opening
the FIFO blocks until the other end is opened also.

A process can open a FIFO in nonblocking mode.  In this case, opening  for
read  only  will  succeed even if no-one has opened on the write side yet,
opening for write only will fail with ENXIO (no such  device  or  address)
unless the other end has already been opened.
```

Opening fifo for writing unblocks `df`:

```
$ echo foo >a.fifo
```

So, basically, we need a way to get the mount point of a file that does not tries to `open()` it in the process. 

Douglas Leeder [suggests in this SO answer](http://stackoverflow.com/a/2167748/2424184) that `stat -c '%m'` might be the answer on Linux, and It works perfectly in my example:

```
$ stat -c '%m' a.fifo
/home
```

I would be happy to propose a PR but I'm not sure on these things:

1. Whether it would work on Mac.
    1. If not, could we simply check `process.platform` and choose the appropriate method?
1. Whether it would be ok to just `spawn()` a stat process here versus requiring some other module for that.

**Comment by kevva** [comment]
Looks like this was [reported](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=29038) and [fixed](https://git.savannah.gnu.org/gitweb/?p=coreutils.git;a=commitdiff;h=b04ce61958c1f1fc264950f8d3b6058f640ee491) in newer versions of `df` (since 8.29).
